<a href="https://colab.research.google.com/github/otaviofernandes/Algebra_Linear/blob/main/Formul%C3%A1rio_%C3%81lgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Cálculo da norma de um vetor#

In [2]:
u = np.array([-3, -6, -2, 10])
norma = np.linalg.norm(u)
norma

12.206555615733702

#Adição de vetores (soma)# 

In [3]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
adicao = a + b
adicao

array([2, 3, 4])

#Inversão de vetores#

In [4]:
a = np.array([3, 6, -1, 5, -2])
inversao = -a
inversao

array([-3, -6,  1, -5,  2])

#Subtração de vetores#
Mesmo que a soma de um vetor com a inversão de outro vetor

In [5]:
a = np.array([3, 2, -4, 1])
b = np.array([1, 5, -1, 0])
subtracao = a + (-b)
subtracao

array([ 2, -3, -3,  1])

#Multiplicação de um vetor por um escalar#

In [6]:
vetor = np.array([3, 2, -4, 1])
escalar = 3
resultante = vetor * escalar
resultante

array([  9,   6, -12,   3])

#Produto Interno#
Multiplicação entre dois vetores
 - operador para produto interno: vetor1 @ vetor2
 - método np.dot(vetor1, vetor2)

In [40]:
a = np.array([-2, 1, 5, -4, 1])
b = np.array([3, 4, 2, -3, 0])
prod_interno = a @ b # operador para produto interno @
print(prod_interno)

c = np.array([1, -2, 1])
d = np.array([3, 2, 2])
prod_interno1 = np.dot(a, b)
print(prod_interno1)

20
20


#Cálculo do angulo entre dois vetores#


In [39]:
u = np.array([12, 8, -4, 20, -16])
v = np.array([-3, -2, -1, -5, -4])

angulo = np.arccos((u@v)/(np.linalg.norm(u)*np.linalg.norm(v)))
print('ângulo em radianos: ', angulo)
print('ângulo em graus: ', (np.rad2deg(angulo)))

ângulo em radianos:  1.9625590494981406
ângulo em graus:  112.44635058144988


#Cálculo do determinante para matrizes 2 x 2 e 3 x 3#
- Obs. se determinante = 0, vetores que compõe a matriz possuem dependência linear

In [18]:
#matriz 2 x 2
m2_2 = np.array([[0, 2],
                 [0, 9]])

#matriz 3 x 3
m3_3 = np.array([[3, 1, 6],
              [2, -1, 3],
              [1, 0, -2]])
determinante2_2 = np.linalg.det(m2_2)
determinante3_3 = np.linalg.det(m3_3)
print('Determinante da matriz 2 x 2: ', determinante2_2)
print('Determinante da matriz 3 x 3: ', determinante3_3)

Determinante da matriz 2 x 2:  0.0
Determinante da matriz 3 x 3:  18.999999999999996


#Soma de matrizes#
- Análogo à soma de vetores, considerando que a matriz é um vetor formado por vetores.

In [12]:
m1 = np.array([[2, 1],
               [1, 3]])
m2 = np.array([[3, 4],
              [5, 7]])
soma_mat = m1 + m2

soma_mat

array([[ 5,  5],
       [ 6, 10]])

#Subtração de matrizes#
- Análogo à subtração de vetores, considerando que a matriz é um vetor formado por vetores.

In [14]:
m3 = np.array([[3, 1, 6],
               [2, -1, 3],
               [1, 0, -2]])
m4 = np.array([[5, -4, 1],
               [-2, -5, 0],
               [-1, 8, 7]])
subtracao_mat = m3 + (-m4)
subtracao_mat

array([[-2,  5,  5],
       [ 4,  4,  3],
       [ 2, -8, -9]])

#Multiplicação de matrizes#
- Análogo ao produto interno de vetores, considerando que a matriz é um vetor formado por vetores.

In [19]:
m5 = np.array([[3, 1, 6],
               [2, -1, 3],
               [1, 0, -2]])
m6 = np.array([[5, -4, 1],
               [-2, -5, 0],
               [-1, 8, 7]])
multiplicacao_mat = np.matmul(m5, m6)
multiplicacao_mat

array([[  7,  31,  45],
       [  9,  21,  23],
       [  7, -20, -13]])

#Transposição de matrizes (matriz transposta)#
$m^T$

In [20]:
m7 = np.array([[3, 1, 6],
               [2, -1, 3],
               [1, 0, -2]])
matriz_transposta = m7.T
matriz_transposta

array([[ 3,  2,  1],
       [ 1, -1,  0],
       [ 6,  3, -2]])

#Inversão de matrizes (matriz inversa)#
- $m^-1$

- $m * m^-1 = I$ (matriz multiplicada pela sua inversa = matriz identidade I)
- Se o determinante da matriz = 0, ela não possuirá inversa.

In [21]:
m8 = np.array([[3, 1],
               [-1, 2]])
inversa = np.linalg.inv(m8)
print('Matriz inversa: ', inversa)

Matriz inversa:  [[ 0.28571429 -0.14285714]
 [ 0.14285714  0.42857143]]
